### ISSUE TITLE
Does not support Microsoft Graph v5

### ISSUE THREAD

**Issue by skst** [windows-toolkit/Graph-Controls#211]
Does CommunityToolkit still support the Graph-Controls library?

If so, it would be great if it could be updated to support Microsoft Graph v5.

## Describe the bug

`ProviderManager.Instance.GlobalProvider.GetClient()` throws `TypeLoadException`.
````
System.TypeLoadException
HResult=0x80131522
Message=Could not load type 'Microsoft.Graph.AuthenticateRequestAsyncDelegate' from assembly 'Microsoft.Graph.Core, Version=3.1.12.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
Source=CommunityToolkit.Graph
StackTrace:
  at CommunityToolkit.Graph.Extensions.ProviderExtensions.GetClient(IProvider provider)
  at CTG5.CTGraph.<<CommunityToolkit_DoOneDriveStuffAsync>g__OnProviderStateChanged|2_0>d.MoveNext() in D:\sandbox\CommunityToolkit.Graph\CTG5.cs:line 40
````

## Steps to Reproduce
1. Unzip the attached project.
2. Insert your client ID in CTG5.cs.
3. Build and run.
4. Click on 'Do Stuff' button.
5. See exception.

## Expected behavior
No exception.

## Environment

NuGet Package(s): 
````
<PackageReference Include="CommunityToolkit.Authentication.Msal" Version="7.1.4" />
<PackageReference Include="CommunityToolkit.Graph" Version="7.1.4" />
<PackageReference Include="Microsoft.Graph" Version="5.56.0" />
<PackageReference Include="Microsoft.Identity.Web.GraphServiceClient" Version="2.19.0" />
````

Windows 10 Build Number:
`<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>`

Device form factor:
- [x] Desktop

Visual Studio 
- [x] 2022.10
```

## Project with error
[CommunityToolkit.Graph v5.zip](https://github.com/user-attachments/files/15709654/CommunityToolkit.Graph.v5.zip)

**Comment by kinex** [comment]
Any workarounds?

**Comment by skst** [comment]
None that I have found.

**Comment by kinex** [comment]
Yeah, back to v4..
